import { ApiProperty } from '@nestjs/swagger';
import { IsEmail, IsNotEmpty, IsOptional, IsString, MinLength } from 'class-validator';

export class CreateSupervisorDto {
    @ApiProperty({ example: 'Sara' })
    @IsString()
    @IsNotEmpty()
    firstName!: string;

    @ApiProperty({ example: 'Hassan' })
    @IsString()
    @IsNotEmpty()
    lastName!: string;

    @ApiProperty({ example: 'sara.hassan@university.edu' })
    @IsEmail()
    @IsNotEmpty()
    email!: string;

    @ApiProperty({ example: '+970592345678' })
    @IsString()
    @IsOptional()
    phone?: string;

    @ApiProperty({ example: 'StrongPass123!' })
    @IsString()
    @MinLength(6)
    @IsNotEmpty()
    password!: string;
    department?: string;

    @ApiProperty({ example: 123456789, required: false, description: 'Optional personal ID; autogenerated if omitted.' })
    @IsOptional()
    personalID?: number;
}
