export const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    UNIVERSITY_ADMIN: 'UNIVERSITY_ADMIN',
    COMPANY_ADMIN: 'COMPANY_ADMIN',
    UNIVERSITY_SUPERVISOR: 'UNIVERSITY_SUPERVISOR',
    COMPANY_TRAINER: 'COMPANY_TRAINER',
    STUDENT: 'STUDENT',
} as const;
